version: 2
jobs:
  build:
    working_directory: ~/workdir
    docker:
      - image: gradle:4.8-jdk8
    steps:
      - checkout
      - restore_cache:
          key: circleci-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: gradle test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global